name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose
    - name: Create Test Files
      run: cp incidents.xmpl incidents.json && cp timestamp.xmpl timestamp.txt
    - name: Install Dotenvx
      run: curl --verbose https://dotenvx.sh/install.sh | sh
    - name: Test
      run: dotenvx run -- cargo test --verbose --all-targets
      env:
        DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}
        RUST_BACKTRACE: 1
